import { expect, test } from '@nuxt/test-utils/playwright'

test('smoke: load the page', async ({ page, goto }) => {
  await goto('/', { waitUntil: 'hydration' })
  await expect(page.getByTestId('project-title')).toHaveText('Coloring, Creative Math, and Computers')
})

test('smoke: basic operations', async ({ page, goto }) => {
  await goto('/', { waitUntil: 'hydration' })
  await expect(page).toHaveScreenshot()
  await page.getByTestId('uncolored-node-list-item-AL').click()
  await expect(page).toHaveScreenshot()
  await page.getByTestId('color-picker-color-red').click()
  await expect(page).toHaveScreenshot()
  await page.locator('#MS').click()
  await expect(page).toHaveScreenshot()
  await page.getByTestId('color-picker-color-blue').click()
  await expect(page).toHaveScreenshot()
  await page.locator('#MS').click()
  await page.getByTestId('color-picker-color-red').click()
  await expect(page).toHaveScreenshot()
  await page.getByText('Alabama and Mississippi are').click()
  await expect(page).toHaveScreenshot()
  await page.getByTestId('color-picker-color-blue').click()
  await expect(page).toHaveScreenshot()
  await page.getByRole('button', { name: 'Auto-Color' }).click()
  await expect(page).toHaveScreenshot()
  await page.getByRole('button', { name: 'Reset' }).click()
  await expect(page).toHaveScreenshot()
})
